
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 12 10:30:03 CST 2026
//----------------------------------------------------

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Jan 12 10:30:03 CST 2026
  */
public class Sintax extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintax() {super();}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintax(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\105\000\002\002\004\000\002\002\003\000\002\002" +
    "\004\000\002\002\004\000\002\002\005\000\002\022\007" +
    "\000\002\021\003\000\002\021\004\000\002\020\010\000" +
    "\002\020\011\000\002\016\006\000\002\016\005\000\002" +
    "\016\005\000\002\016\004\000\002\003\003\000\002\003" +
    "\004\000\002\004\004\000\002\004\004\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\025\003\000\002\006\004\000\002\006" +
    "\005\000\002\005\013\000\002\005\011\000\002\005\007" +
    "\000\002\005\006\000\002\005\004\000\002\024\004\000" +
    "\002\024\005\000\002\023\014\000\002\023\012\000\002" +
    "\023\010\000\002\023\007\000\002\023\005\000\002\007" +
    "\005\000\002\007\005\000\002\007\004\000\002\007\004" +
    "\000\002\007\012\000\002\007\010\000\002\012\007\000" +
    "\002\012\011\000\002\013\007\000\002\014\013\000\002" +
    "\014\013\000\002\015\011\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\005\000\002\011\006" +
    "\000\002\011\005\000\002\011\005\000\002\011\005\000" +
    "\002\011\005\000\002\026\003\000\002\026\005\000\002" +
    "\017\005\000\002\017\003\000\002\017\005\000\002\017" +
    "\005\000\002\010\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\245\000\014\010\012\011\006\012\013\013\011\014" +
    "\015\001\002\000\004\002\247\001\002\000\004\044\233" +
    "\001\002\000\006\044\uffea\047\uffea\001\002\000\004\010" +
    "\ufffb\001\002\000\004\002\000\001\002\000\006\044\uffe8" +
    "\047\uffe8\001\002\000\010\015\031\043\030\044\uffeb\001" +
    "\002\000\006\044\uffe9\047\uffe9\001\002\000\004\010\027" +
    "\001\002\000\006\044\uffe7\047\uffe7\001\002\000\014\010" +
    "\012\011\006\012\013\013\011\014\015\001\002\000\004" +
    "\045\020\001\002\000\014\010\uffdf\011\uffdf\012\uffdf\013" +
    "\uffdf\014\uffdf\001\002\000\004\002\ufffe\001\002\000\004" +
    "\010\027\001\002\000\004\045\024\001\002\000\014\010" +
    "\uffde\011\uffde\012\uffde\013\uffde\014\uffde\001\002\000\004" +
    "\002\ufffd\001\002\000\004\010\ufffa\001\002\000\006\015" +
    "\031\043\030\001\002\000\004\035\227\001\002\000\004" +
    "\047\032\001\002\000\004\035\033\001\002\000\016\010" +
    "\037\011\006\012\013\013\011\014\015\036\035\001\002" +
    "\000\004\047\214\001\002\000\004\037\044\001\002\000" +
    "\016\010\037\011\006\012\013\013\011\014\015\036\043" +
    "\001\002\000\004\047\uffeb\001\002\000\004\045\041\001" +
    "\002\000\036\005\uffe6\010\uffe6\011\uffe6\012\uffe6\013\uffe6" +
    "\014\uffe6\016\uffe6\020\uffe6\021\uffe6\022\uffe6\031\uffe6\036" +
    "\uffe6\040\uffe6\047\uffe6\001\002\000\004\045\212\001\002" +
    "\000\004\037\044\001\002\000\034\005\061\010\037\011" +
    "\006\012\013\013\011\014\015\016\060\020\063\021\065" +
    "\022\046\031\057\040\051\047\050\001\002\000\004\010" +
    "\ufff8\001\002\000\004\035\173\001\002\000\022\005\061" +
    "\016\060\020\063\021\065\022\046\031\057\040\172\047" +
    "\050\001\002\000\012\023\155\031\154\033\152\041\153" +
    "\001\002\000\030\002\ufff4\005\ufff4\010\ufff4\016\ufff4\017" +
    "\ufff4\020\ufff4\021\ufff4\022\ufff4\031\ufff4\040\ufff4\047\ufff4" +
    "\001\002\000\004\045\151\001\002\000\022\005\ufff3\016" +
    "\ufff3\020\ufff3\021\ufff3\022\ufff3\031\ufff3\040\ufff3\047\ufff3" +
    "\001\002\000\022\005\uffef\016\uffef\020\uffef\021\uffef\022" +
    "\uffef\031\uffef\040\uffef\047\uffef\001\002\000\022\005\uffee" +
    "\016\uffee\020\uffee\021\uffee\022\uffee\031\uffee\040\uffee\047" +
    "\uffee\001\002\000\022\005\uffec\016\uffec\020\uffec\021\uffec" +
    "\022\uffec\031\uffec\040\uffec\047\uffec\001\002\000\004\047" +
    "\150\001\002\000\004\035\142\001\002\000\012\007\101" +
    "\035\110\047\077\050\074\001\002\000\004\045\140\001" +
    "\002\000\004\037\044\001\002\000\022\005\uffed\016\uffed" +
    "\020\uffed\021\uffed\022\uffed\031\uffed\040\uffed\047\uffed\001" +
    "\002\000\004\035\073\001\002\000\034\005\061\010\037" +
    "\011\006\012\013\013\011\014\015\016\060\020\063\021" +
    "\065\022\046\031\057\040\070\047\050\001\002\000\022" +
    "\005\061\016\060\020\063\021\065\022\046\031\057\040" +
    "\072\047\050\001\002\000\030\002\ufff5\005\ufff5\010\ufff5" +
    "\016\ufff5\017\ufff5\020\ufff5\021\ufff5\022\ufff5\031\ufff5\040" +
    "\ufff5\047\ufff5\001\002\000\022\005\ufff2\016\ufff2\020\ufff2" +
    "\021\ufff2\022\ufff2\031\ufff2\040\ufff2\047\ufff2\001\002\000" +
    "\030\002\ufff7\005\ufff7\010\ufff7\016\ufff7\017\ufff7\020\ufff7" +
    "\021\ufff7\022\ufff7\031\ufff7\040\ufff7\047\ufff7\001\002\000" +
    "\014\007\101\034\076\035\075\047\077\050\074\001\002" +
    "\000\030\024\uffcc\025\uffcc\026\uffcc\027\uffcc\030\uffcc\032" +
    "\uffcc\036\uffcc\040\uffcc\042\uffcc\045\uffcc\046\uffcc\001\002" +
    "\000\014\007\101\034\076\035\075\047\077\050\074\001" +
    "\002\000\010\030\uffc0\036\uffc0\045\uffc0\001\002\000\032" +
    "\024\uffcb\025\uffcb\026\uffcb\027\uffcb\030\uffcb\032\uffcb\036" +
    "\uffcb\040\uffcb\041\124\042\uffcb\045\uffcb\046\uffcb\001\002" +
    "\000\006\030\120\036\121\001\002\000\030\024\uffca\025" +
    "\uffca\026\uffca\027\uffca\030\uffca\032\uffca\036\uffca\040\uffca" +
    "\042\uffca\045\uffca\046\uffca\001\002\000\014\024\106\025" +
    "\105\026\107\027\103\032\104\001\002\000\012\007\101" +
    "\035\110\047\077\050\074\001\002\000\012\007\101\035" +
    "\110\047\077\050\074\001\002\000\012\007\101\035\110" +
    "\047\077\050\074\001\002\000\012\007\101\035\110\047" +
    "\077\050\074\001\002\000\012\007\101\035\110\047\077" +
    "\050\074\001\002\000\012\007\101\035\110\047\077\050" +
    "\074\001\002\000\030\024\uffc5\025\uffc5\026\uffc5\027\uffc5" +
    "\030\uffc5\032\uffc5\036\uffc5\040\uffc5\042\uffc5\045\uffc5\046" +
    "\uffc5\001\002\000\014\024\106\025\105\026\107\027\103" +
    "\036\113\001\002\000\030\024\uffc9\025\uffc9\026\uffc9\027" +
    "\uffc9\030\uffc9\032\uffc9\036\uffc9\040\uffc9\042\uffc9\045\uffc9" +
    "\046\uffc9\001\002\000\030\024\uffc7\025\uffc7\026\107\027" +
    "\103\030\uffc7\032\uffc7\036\uffc7\040\uffc7\042\uffc7\045\uffc7" +
    "\046\uffc7\001\002\000\030\024\uffc6\025\uffc6\026\107\027" +
    "\103\030\uffc6\032\uffc6\036\uffc6\040\uffc6\042\uffc6\045\uffc6" +
    "\046\uffc6\001\002\000\020\024\106\025\105\026\107\027" +
    "\103\030\uffc1\036\uffc1\045\uffc1\001\002\000\030\024\uffc4" +
    "\025\uffc4\026\uffc4\027\uffc4\030\uffc4\032\uffc4\036\uffc4\040" +
    "\uffc4\042\uffc4\045\uffc4\046\uffc4\001\002\000\014\007\101" +
    "\034\076\035\075\047\077\050\074\001\002\000\004\037" +
    "\044\001\002\000\022\005\uffd0\016\uffd0\020\uffd0\021\uffd0" +
    "\022\uffd0\031\uffd0\040\uffd0\047\uffd0\001\002\000\010\030" +
    "\uffbf\036\uffbf\045\uffbf\001\002\000\012\007\101\035\110" +
    "\047\077\050\074\001\002\000\014\024\106\025\105\026" +
    "\107\027\103\042\126\001\002\000\030\024\uffc8\025\uffc8" +
    "\026\uffc8\027\uffc8\030\uffc8\032\uffc8\036\uffc8\040\uffc8\042" +
    "\uffc8\045\uffc8\046\uffc8\001\002\000\006\030\120\036\131" +
    "\001\002\000\016\024\106\025\105\026\107\027\103\032" +
    "\104\036\113\001\002\000\010\030\uffbe\036\uffbe\045\uffbe" +
    "\001\002\000\004\021\133\001\002\000\004\035\134\001" +
    "\002\000\014\007\101\034\076\035\075\047\077\050\074" +
    "\001\002\000\006\030\120\036\136\001\002\000\004\045" +
    "\137\001\002\000\022\005\uffcd\016\uffcd\020\uffcd\021\uffcd" +
    "\022\uffcd\031\uffcd\040\uffcd\047\uffcd\001\002\000\022\005" +
    "\ufff0\016\ufff0\020\ufff0\021\ufff0\022\ufff0\031\ufff0\040\ufff0" +
    "\047\ufff0\001\002\000\014\024\106\025\105\026\107\027" +
    "\103\045\uffbd\001\002\000\014\007\101\034\076\035\075" +
    "\047\077\050\074\001\002\000\006\030\120\036\144\001" +
    "\002\000\004\037\044\001\002\000\024\005\uffd2\016\uffd2" +
    "\017\146\020\uffd2\021\uffd2\022\uffd2\031\uffd2\040\uffd2\047" +
    "\uffd2\001\002\000\004\037\044\001\002\000\022\005\uffd1" +
    "\016\uffd1\020\uffd1\021\uffd1\022\uffd1\031\uffd1\040\uffd1\047" +
    "\uffd1\001\002\000\006\036\uffd5\045\uffd5\001\002\000\022" +
    "\005\ufff1\016\ufff1\020\ufff1\021\ufff1\022\ufff1\031\ufff1\040" +
    "\ufff1\047\ufff1\001\002\000\012\007\101\035\110\047\077" +
    "\050\074\001\002\000\012\007\101\035\110\047\077\050" +
    "\074\001\002\000\006\036\uffd6\045\uffd6\001\002\000\012" +
    "\007\101\035\110\047\077\050\074\001\002\000\016\024" +
    "\106\025\105\026\107\027\103\036\uffd8\045\uffd8\001\002" +
    "\000\014\024\106\025\105\026\107\027\103\042\160\001" +
    "\002\000\004\023\161\001\002\000\014\007\101\035\110" +
    "\037\162\047\077\050\074\001\002\000\012\007\101\035" +
    "\110\047\077\050\074\001\002\000\016\024\106\025\105" +
    "\026\107\027\103\036\uffd3\045\uffd3\001\002\000\006\040" +
    "\166\046\167\001\002\000\016\024\106\025\105\026\107" +
    "\027\103\040\uffc3\046\uffc3\001\002\000\006\036\uffd4\045" +
    "\uffd4\001\002\000\012\007\101\035\110\047\077\050\074" +
    "\001\002\000\016\024\106\025\105\026\107\027\103\040" +
    "\uffc2\046\uffc2\001\002\000\016\024\106\025\105\026\107" +
    "\027\103\036\uffd7\045\uffd7\001\002\000\030\002\ufff6\005" +
    "\ufff6\010\ufff6\016\ufff6\017\ufff6\020\ufff6\021\ufff6\022\ufff6" +
    "\031\ufff6\040\ufff6\047\ufff6\001\002\000\020\010\037\011" +
    "\006\012\013\013\011\014\015\031\057\047\050\001\002" +
    "\000\004\045\204\001\002\000\004\045\176\001\002\000" +
    "\014\007\101\034\076\035\075\047\077\050\074\001\002" +
    "\000\006\030\120\045\200\001\002\000\006\031\057\047" +
    "\050\001\002\000\004\036\202\001\002\000\004\037\044" +
    "\001\002\000\022\005\uffce\016\uffce\020\uffce\021\uffce\022" +
    "\uffce\031\uffce\040\uffce\047\uffce\001\002\000\014\007\101" +
    "\034\076\035\075\047\077\050\074\001\002\000\006\030" +
    "\120\045\206\001\002\000\006\031\057\047\050\001\002" +
    "\000\004\036\210\001\002\000\004\037\044\001\002\000" +
    "\022\005\uffcf\016\uffcf\020\uffcf\021\uffcf\022\uffcf\031\uffcf" +
    "\040\uffcf\047\uffcf\001\002\000\036\005\uffe5\010\uffe5\011" +
    "\uffe5\012\uffe5\013\uffe5\014\uffe5\016\uffe5\020\uffe5\021\uffe5" +
    "\022\uffe5\031\uffe5\036\uffe5\040\uffe5\047\uffe5\001\002\000" +
    "\004\010\ufff9\001\002\000\010\023\216\041\215\045\uffe0" +
    "\001\002\000\004\050\220\001\002\000\012\007\101\035" +
    "\110\047\077\050\074\001\002\000\014\024\106\025\105" +
    "\026\107\027\103\045\uffe1\001\002\000\004\042\221\001" +
    "\002\000\006\023\222\045\uffe2\001\002\000\014\007\101" +
    "\035\110\037\223\047\077\050\074\001\002\000\012\007" +
    "\101\035\110\047\077\050\074\001\002\000\014\024\106" +
    "\025\105\026\107\027\103\045\uffe3\001\002\000\006\040" +
    "\226\046\167\001\002\000\004\045\uffe4\001\002\000\004" +
    "\036\230\001\002\000\004\037\044\001\002\000\004\002" +
    "\ufffc\001\002\000\004\002\uffff\001\002\000\004\047\234" +
    "\001\002\000\010\023\236\041\235\045\uffd9\001\002\000" +
    "\004\050\240\001\002\000\012\007\101\035\110\047\077" +
    "\050\074\001\002\000\014\024\106\025\105\026\107\027" +
    "\103\045\uffda\001\002\000\004\042\241\001\002\000\006" +
    "\023\242\045\uffdb\001\002\000\014\007\101\035\110\037" +
    "\243\047\077\050\074\001\002\000\012\007\101\035\110" +
    "\047\077\050\074\001\002\000\014\024\106\025\105\026" +
    "\107\027\103\045\uffdc\001\002\000\006\040\246\046\167" +
    "\001\002\000\004\045\uffdd\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\245\000\020\002\003\020\006\021\013\022\007\023" +
    "\016\024\015\025\004\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\020\025\022\231\001\001\000\002\001\001\000" +
    "\014\020\006\021\021\022\020\023\022\025\004\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\020\025\022\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\005\037\006\035\025\033\001\001\000\002\001" +
    "\001\000\004\016\212\001\001\000\006\005\041\025\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\016\044\001\001\000\030" +
    "\003\046\004\052\005\037\006\065\007\051\010\061\012" +
    "\053\013\054\014\063\015\055\025\033\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\004\070\007\051\010" +
    "\061\012\053\013\054\014\063\015\055\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\140\001" +
    "\001\000\002\001\001\000\004\016\131\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\003\066\004\052\005" +
    "\041\007\051\010\061\012\053\013\054\014\063\015\055" +
    "\025\033\001\001\000\020\004\070\007\051\010\061\012" +
    "\053\013\054\014\063\015\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\011\101\017" +
    "\077\001\001\000\002\001\001\000\006\011\127\017\126" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\116" +
    "\001\001\000\004\011\115\001\001\000\004\011\114\001" +
    "\001\000\004\011\113\001\001\000\004\011\110\001\001" +
    "\000\004\011\111\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\011\101\017" +
    "\122\001\001\000\004\016\121\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\124\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\011\101\017\134\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\011\101\017\142\001\001\000\002\001\001" +
    "\000\004\016\144\001\001\000\002\001\001\000\004\016" +
    "\146\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\170\001\001\000\004\011\156\001" +
    "\001\000\002\001\001\000\004\011\155\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\162\001\001\000\006\011\164\026\163\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\167\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\005\174\007\173\025" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\101\017\176\001\001\000\002\001\001\000\004\007" +
    "\200\001\001\000\002\001\001\000\004\016\202\001\001" +
    "\000\002\001\001\000\006\011\101\017\204\001\001\000" +
    "\002\001\001\000\004\007\206\001\001\000\002\001\001" +
    "\000\004\016\210\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\216\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\011\223\001\001\000\006" +
    "\011\164\026\224\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\016\230" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\236" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\243\001\001\000\006\011\164\026\244" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    private int erroresSintacticos = 0;
    private final int MAX_ERRORES = 10;
    
    public void syntax_error(Symbol s){
        this.s = s;
        erroresSintacticos++;
        
        System.err.println("ERROR SINTÁCTICO en línea " + (s.left+1) + 
                          ", columna " + (s.right+1) + 
                          ": Token inesperado '" + s.value + "'");
        
        if (erroresSintacticos < MAX_ERRORES) {
            System.err.println("  Recuperando... (Modo Pánico)");
            
            buscarPuntoRecuperacion();
            
            System.err.println("  Continuando análisis...");
        } else {
            System.err.println("DEMASIADOS ERRORES. Análisis abortado.");
            done_parsing();
        }
    }
    
    private void buscarPuntoRecuperacion() {
        Symbol token;
        try {
            do {
                token = getScanner().next_token();
                if (token.sym == sym.EOF) {
                    System.err.println("  Fin de archivo alcanzado");
                    done_parsing();
                    return;
                }
            } while (token.sym != sym.P_coma && 
                     token.sym != sym.Llave_c && 
                     token.sym != sym.Parentesis_c);
            
            System.err.println("  Recuperado en línea " + (token.left+1));
        } catch (Exception e) {
            System.err.println("  Error durante recuperación: " + e.getMessage());
        }
    }
    
    public Symbol getS(){
        return this.s;
    }
    
    public int getErroresSintacticos() {
        return erroresSintacticos;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintax$actions {
  private final Sintax parser;

  /** Constructor */
  CUP$Sintax$actions(Sintax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintax$do_action(
    int                        CUP$Sintax$act_num,
    java_cup.runtime.lr_parser CUP$Sintax$parser,
    java.util.Stack            CUP$Sintax$stack,
    int                        CUP$Sintax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintax$result;

      /* select the action based on the action number */
      switch (CUP$Sintax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // retorno ::= Return expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("retorno",6, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr_logica ::= Parentesis_a expr_logica Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr_logica ::= expr_logica Op_logico expr_logica 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr_logica ::= Op_booleano 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr_logica ::= expresion Op_relacional expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expr_logica",13, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_expresiones ::= lista_expresiones Coma expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("lista_expresiones",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // lista_expresiones ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("lista_expresiones",20, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= expresion Division expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= expresion Multiplicacion expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= expresion Resta expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= expresion Suma expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= Identificador Corchete_a expresion Corchete_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= Parentesis_a expresion Parentesis_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= Cadena 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= Numero 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("expresion",7, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // ciclo_do ::= Do bloque While Parentesis_a expr_logica Parentesis_c P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ciclo_do",11, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // ciclo_for ::= For Parentesis_a declaracion P_coma expr_logica P_coma asignacion Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ciclo_for",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ciclo_for ::= For Parentesis_a asignacion P_coma expr_logica P_coma asignacion Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ciclo_for",10, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ciclo_while ::= While Parentesis_a expr_logica Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("ciclo_while",9, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // condicional ::= If Parentesis_a expr_logica Parentesis_c bloque Else bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("condicional",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // condicional ::= If Parentesis_a expr_logica Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("condicional",8, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // asignacion ::= Identificador Corchete_a expresion Corchete_c Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // asignacion ::= Identificador Corchete_a expresion Corchete_c Igual Llave_a lista_expresiones Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // asignacion ::= Op_incremento Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // asignacion ::= Identificador Op_incremento 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // asignacion ::= Identificador Op_atribucion expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // asignacion ::= Identificador Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("asignacion",5, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // declaracion_global ::= tipo_de_variable World Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion_global",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // declaracion_global ::= tipo_de_variable World Identificador Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion_global",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declaracion_global ::= tipo_de_variable World Identificador Corchete_a Numero Corchete_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion_global",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declaracion_global ::= tipo_de_variable World Identificador Corchete_a Numero Corchete_c Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion_global",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-7)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declaracion_global ::= tipo_de_variable World Identificador Corchete_a Numero Corchete_c Igual Llave_a lista_expresiones Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion_global",17, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-9)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declaraciones_globales ::= declaraciones_globales declaracion_global P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaraciones_globales",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declaraciones_globales ::= declaracion_global P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaraciones_globales",18, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declaracion ::= tipo_de_variable Identificador 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declaracion ::= tipo_de_variable Identificador Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // declaracion ::= tipo_de_variable Identificador Corchete_a Numero Corchete_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // declaracion ::= tipo_de_variable Identificador Corchete_a Numero Corchete_c Igual expresion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declaracion ::= tipo_de_variable Identificador Corchete_a Numero Corchete_c Igual Llave_a lista_expresiones Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-8)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaraciones ::= declaraciones declaracion P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaraciones",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declaraciones ::= declaracion P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("declaraciones",4, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_de_variable ::= String 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("tipo_de_variable",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_de_variable ::= Char 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("tipo_de_variable",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_de_variable ::= Bool 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("tipo_de_variable",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_de_variable ::= Float 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("tipo_de_variable",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo_de_variable ::= Int 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("tipo_de_variable",19, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // sentencia ::= ciclo_do 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // sentencia ::= ciclo_for 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // sentencia ::= ciclo_while 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // sentencia ::= condicional 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // sentencia ::= retorno P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= asignacion P_coma 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencias",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("sentencias",1, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // bloque ::= Llave_a Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("bloque",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // bloque ::= Llave_a declaraciones Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("bloque",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // bloque ::= Llave_a sentencias Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("bloque",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // bloque ::= Llave_a declaraciones sentencias Llave_c 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("bloque",12, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-3)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // funcion ::= Int Func Identificador Parentesis_a declaraciones Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("funcion",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-6)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // funcion ::= Int Func Identificador Parentesis_a Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("funcion",14, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-5)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // funciones ::= funciones funcion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("funciones",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // funciones ::= funcion 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("funciones",15, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // main ::= Int Navidad Parentesis_a Parentesis_c bloque 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("main",16, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-4)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= declaraciones_globales funciones main 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-2)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= declaraciones_globales main 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= funciones main 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= main 
            {
              Object RESULT =null;

              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          return CUP$Sintax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)).value;
		RESULT = start_val;
              CUP$Sintax$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintax$stack.elementAt(CUP$Sintax$top-1)), ((java_cup.runtime.Symbol)CUP$Sintax$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintax$parser.done_parsing();
          return CUP$Sintax$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

