
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 26 10:50:45 CST 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 6;
  public static final int Parentesis_c = 18;
  public static final int For = 9;
  public static final int Parentesis_a = 17;
  public static final int Suma = 13;
  public static final int Numero = 11;
  public static final int Op_booleano = 26;
  public static final int ERROR = 27;
  public static final int Identificador = 10;
  public static final int Int = 2;
  public static final int Llave_c = 20;
  public static final int Llave_a = 19;
  public static final int Op_relacional = 22;
  public static final int P_coma = 21;
  public static final int Navidad = 3;
  public static final int EOF = 0;
  public static final int Division = 16;
  public static final int Op_atribucion = 25;
  public static final int Op_incremento = 24;
  public static final int Resta = 14;
  public static final int If = 5;
  public static final int Return = 4;
  public static final int error = 1;
  public static final int Op_logico = 23;
  public static final int Do = 8;
  public static final int Igual = 12;
  public static final int While = 7;
  public static final int Multiplicacion = 15;
}

