
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 11 22:23:31 CST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 24;
  public static final int Llave_c = 30;
  public static final int Op_booleano = 26;
  public static final int Llave_a = 29;
  public static final int If = 12;
  public static final int Else = 13;
  public static final int Func = 11;
  public static final int World = 34;
  public static final int Corchete_c = 32;
  public static final int Corchete_a = 31;
  public static final int Return = 3;
  public static final int While = 15;
  public static final int Division = 21;
  public static final int Int = 6;
  public static final int Cadena = 5;
  public static final int Float = 7;
  public static final int Parentesis_c = 28;
  public static final int Parentesis_a = 27;
  public static final int For = 16;
  public static final int P_coma = 35;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Char = 9;
  public static final int Op_atribucion = 25;
  public static final int Do = 14;
  public static final int ERROR = 2;
  public static final int Op_logico = 22;
  public static final int String = 10;
  public static final int Navidad = 33;
  public static final int Identificador = 36;
  public static final int Resta = 19;
  public static final int Bool = 8;
  public static final int Multiplicacion = 20;
  public static final int Op_incremento = 23;
  public static final int Numero = 37;
  public static final int Suma = 18;
  public static final int Igual = 17;
  public static final int Comillas = 4;
}

