
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 31 19:59:32 CST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 40;
  public static final int Entero = 5;
  public static final int True = 7;
  public static final int Coma = 58;
  public static final int End = 27;
  public static final int Negacion = 51;
  public static final int Of = 25;
  public static final int Diferente = 47;
  public static final int Potencia = 38;
  public static final int Decide = 24;
  public static final int Menor = 41;
  public static final int Else = 26;
  public static final int World = 16;
  public static final int Break = 19;
  public static final int Corchete_c = 60;
  public static final int Corchete_a = 59;
  public static final int Mayor = 43;
  public static final int Division_entera = 36;
  public static final int S_exclamacion_c = 55;
  public static final int Return = 18;
  public static final int S_exclamacion_a = 54;
  public static final int Division = 35;
  public static final int Int = 9;
  public static final int Flotante = 6;
  public static final int Doble_igual = 46;
  public static final int Cadena = 3;
  public static final int Float = 10;
  public static final int Modulo = 37;
  public static final int Conjuncion = 49;
  public static final int For = 31;
  public static final int Gift = 20;
  public static final int P_coma = 57;
  public static final int EOF = 0;
  public static final int Local = 17;
  public static final int Mayor_igual = 44;
  public static final int error = 1;
  public static final int Disyuncion = 50;
  public static final int When = 30;
  public static final int Show = 22;
  public static final int False = 8;
  public static final int Flecha = 48;
  public static final int Get = 23;
  public static final int Char = 12;
  public static final int ERROR = 2;
  public static final int Menor_igual = 42;
  public static final int String = 13;
  public static final int Navidad = 21;
  public static final int Identificador = 15;
  public static final int Endl = 56;
  public static final int S_pregunta_c = 53;
  public static final int Resta = 33;
  public static final int S_pregunta_a = 52;
  public static final int Caracter = 4;
  public static final int Coal = 14;
  public static final int Bool = 11;
  public static final int Multiplicacion = 34;
  public static final int Op_incremento = 39;
  public static final int Suma = 32;
  public static final int Exit = 29;
  public static final int Loop = 28;
  public static final int Igual = 45;
}

